# Generated by Django 5.0.3 on 2024-03-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_inning',
            field=models.IntegerField(default=1),
        ),
    ]
